server:
  port: 8050

spring:
  application:
    name: tlmall-user-config-demo
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - nacos:nacos-discovery.yml     #nacos注册中心配置
  cloud:
    nacos:
      config:
        server-addr: tlmall-nacos-server:8848
        username: nacos
        password: nacos


