server:
  port: 8060
spring:
  application:
    name: tlmall-order-config-demo
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        server-addr: tlmall-nacos-server:8848
        namespace: fox
        username: nacos
        password: nacos
  config:
    import:
      - optional:nacos:${spring.application.name}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml
      - optional:nacos:db-common.yml  #数据库公共配置
      - nacos:nacos-discovery.yml #nacos注册中心配置
      #- nacos:cipher-aes-nacos-discovery.yml  #拉取加密的nacos注册中心配置
order:
  count: 10


logging:
  level:
    com.alibaba.cloud.nacos: debug
